#!/bin/sh
I2PDATADIR="$XDG_DATA_HOME/.i2pd"

if [ ! -d "$I2PDATADIR" ]; then
    mkdir -p $I2PDATADIR
    cp /app/i2pd/i2pd.conf $I2PDATADIR
    cp /app/i2pd/tunnels.conf $I2PDATADIR
    ln -s /app/i2pd/certificates $I2PDATADIR/certificates
fi

ulimit -n 8192
i2pd_qt --datadir=$I2PDATADIR
